variables:
    SolutionBaseName: 'NCS.DSS.Transfer'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (CDH)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

jobs:
# Build the app with the dfc-dotnetcore-build template.
- job: BuildDotNetStandard
  displayName: Build-DotNetStandard

  steps:
  - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcorefunctionapp-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)





